common/models/User.php
<?php
namespace common\models;

use Yii;  
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 10;


    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [   
            [['email','name','phone','mobile','address'],'required','on'=>'update'],           
            [['name','phone','mobile','address'],'safe'],
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
        ];
    }
              
    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return bool
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
}

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\User;
use common\models\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $this->layout= 'container';                                                                          
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $this->layout= 'container';                                                                          
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $this->layout= 'container';                                                                          
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed    
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $this->layout= 'container';                                                                          
        $model = $this->findModel($id);               
        unset($_POST['ChangePasswordForm']);                      
		$model = $this->findModel($id);              
		$model->scenario = 'update';      
        $changePasswordModel = new \backend\models\ChangePasswordForm;        
             
        if ($model->load(Yii::$app->request->post()) && $model->save()) {  
            return $this->redirect(['view', 'id' => $model->id]);
        }   
              
        return $this->render('update', [ 
            'model' => $model,'changePasswordModel'=>$changePasswordModel
        ]);
    } 

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->layout= 'container';                                                                          
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionChangepassword($id){    
		if(Yii::$app->request->isAjax){
			$changePasswordModel = new \backend\models\ChangePasswordForm;
			$model = \common\models\User::findOne($id);  
            $changePasswordModel->scenario = 'update';
			if($changePasswordModel->load(Yii::$app->request->post()) && $changePasswordModel->validate()){
				
				$model->setPassword($changePasswordModel->confirm_password);   
				$model->save(false);
				echo json_encode([
				'success'=>1,    
				'data'=>$this->renderAjax('change-pass-form', [
                'changePasswordModel'=>$changePasswordModel,'model'=>$model
            ])
			]);
			}else{
				echo json_encode([
				'success'=>0,
				'data'=>$this->renderAjax('change-pass-form', [
                 'changePasswordModel'=>$changePasswordModel,'model'=>$model
				])
			]);
			}
			
				
			
			Yii::$app->end();         
			
		}
	}
}

backend/views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;  

/* @var $this yii\web\View */
/* @var $model common\models\User */
/* @var $form yii\widgets\ActiveForm */
?>
<?php if($model->isNewRecord):?>     

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput() ?>        
    <?= $form->field($model, 'phone')->textInput() ?>        
    <?= $form->field($model, 'mobile')->textInput() ?>        
    <?= $form->field($model, 'address')->textInput() ?>        
    <?= $form->field($model, 'email')->textInput() ?>  

    <?= $form->field($model, 'status')->textInput() ?>        


    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
<?php else:?>  
<div class="updateContents">          
			<div class="alert alert-success alert-dismissible chng-pass" style="display:none">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-check"></i> Success!</h4>
                Password changed.
			</div>
            <div class="nav-tabs-custom">
                <ul class="nav nav-tabs">
                  <li class="active"><a href="#tab_1" data-toggle="tab" aria-expanded="true">Update Profile</a></li>
                  <li class=""><a href="#tab_2" data-toggle="tab" aria-expanded="false">Change Password</a></li>
                  
                 </ul>  
                
                <?php $form = ActiveForm::begin(['id'=>'change-password']); ?>     
                <div class="tab-content">	
                         
                    <div class="tab-pane active" id="tab_1">      
                        <div class="user-form">          
                
                            <?= $form->field($model, 'name')->textInput() ?>        
                            <?= $form->field($model, 'phone')->textInput() ?>        
                            <?= $form->field($model, 'mobile')->textInput() ?>        
                            <?= $form->field($model, 'address')->textInput() ?>  
                            <?= $form->field($model, 'email')->textInput() ?>
                            <?= $form->field($model, 'status')->textInput() ?>
                            
                            <?php /* $form->field($model, 'status')->dropDownList(common\components\Helper::$status) */?>
                
                            <div class="form-group">
                                <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                            </div>
                
                        </div>   
                            
                    </div>
                  <!-- /.tab-pane -->
                    <div class="tab-pane" id="tab_2">
                        <?php echo $this->renderAjax('change-pass-form', [
                        'changePasswordModel'=>$changePasswordModel,'model'=>$model,'form'=>$form
                    ]);?>
                    </div>
                <!-- /.tab-content -->  
                 <?php ActiveForm::end(); ?>
            </div>
            </div>
        </div>       
<style>  

    .nav-tabs-custom>.nav-tabs>li:first-of-type.active>a {
        border-left-color: transparent;
    }
    .nav-tabs-custom>.nav-tabs>li.active>a {
        border-top-color: transparent;
        border-left-color: #f4f4f4;
        border-right-color: #f4f4f4;
    }
    .nav-tabs-custom>.nav-tabs>li.active>a, .nav-tabs-custom>.nav-tabs>li.active:hover>a {
        background-color: #fff;
        color: #444;
    }
    .nav-tabs-custom>.nav-tabs>li>a, .nav-tabs-custom>.nav-tabs>li>a:hover {
        background: transparent;
        margin: 0;
    }
    .nav-tabs-custom>.nav-tabs>li>a {
        color: #444;
        border-radius: 0;
    }
    .nav-tabs>li.active>a, .nav-tabs>li.active>a:focus, .nav-tabs>li.active>a:hover {
        color: #555;
        cursor: default;
        background-color: #fff;
        border: 1px solid #ddd;
        border-bottom-color: transparent;
    }
    .nav-tabs>li>a {
        margin-right: 2px;
        line-height: 1.42857143;
        border: 1px solid transparent;
        border-radius: 4px 4px 0 0;
    }
    .nav>li>a {
        position: relative;
        display: block;
        padding: 10px 15px;
    }
    .nav-tabs-custom>.nav-tabs>li:not(.active)>a:hover, .nav-tabs-custom>.nav-tabs>li:not(.active)>a:focus, .nav-tabs-custom>.nav-tabs>li:not(.active)>a:active {
        border-color: transparent;
    }
    .nav-tabs-custom>.nav-tabs>li>a:hover {
        color: #999;
    }
    .nav-tabs-custom>.nav-tabs>li>a, .nav-tabs-custom>.nav-tabs>li>a:hover {
        background: transparent;
        margin: 0;
    }
    .nav-tabs-custom>.nav-tabs>li>a {
        color: #444;
        border-radius: 0;
    }
    .nav>li>a:hover, .nav>li>a:active, .nav>li>a:focus {
        color: #444;
        background: #f7f7f7;
    }
    .nav-tabs>li>a:hover {
        border-color: #eee #eee #ddd;
    }
    .nav>li>a:focus, .nav>li>a:hover {
        text-decoration: none;
        background-color: #eee;
    }
    .nav-tabs>li>a {
        margin-right: 2px;
        line-height: 1.42857143;
        border: 1px solid transparent;
        border-radius: 4px 4px 0 0;
    }
    .nav>li>a {
        position: relative;
        display: block;
        padding: 10px 15px;
    }
    a:hover, a:active, a:focus {
        outline: none;
        text-decoration: none;
        color: #72afd2;
    }
</style>
<?php
$js =<<<JS
	$("body").on("click",'#changepassword',function(ev){   
		ev.preventDefault();  
		
		var obj = $(this);
		$.ajax({
			type:'post',
			url:obj.data('aurl'),
			data:$("body #change-password").serialize(),     
			dataType:'json',
			success:function(res){
				if(res.success==1){
					$("body #change-password")[0].reset();
					$("body .chng-pass").show().delay(5000).fadeOut();
				}else{
					$("body #tab_2").html(res.data);
				}
			}
		})
		});
JS;
$this->registerJS($js);           
?>
<?php endif;?>

backend/views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'auth_key') ?>

    <?= $form->field($model, 'password_hash') ?>

    <?= $form->field($model, 'password_reset_token') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/user/change-pass-form.php
<?php 

use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>

<?php if(Yii::$app->controller->action->id=='changepassword'):?>
 
<?php $form = ActiveForm::begin(['id'=>'change-password']); ?>     
<?php endif;?>        
<div class="cp-form">
	<?= $form->field($changePasswordModel, 'old_password')->passwordInput() ?>  
	<?= $form->field($changePasswordModel, 'new_password')->passwordInput() ?>   
	<?= $form->field($changePasswordModel, 'confirm_password')->passwordInput() ?>
   
	<div class="form-group">
		<?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Change') : Yii::t('app', 'Change'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary',
		'id'=>'changepassword','data-aurl'=>Yii::$app->urlManager->createUrl(['user/changepassword','id'=>$model->id]),
		'data-formid'=>'changepassword']) ?>
	</div>
</div>
<?php if(Yii::$app->controller->action->id=='changepassword'):?>
<?php ActiveForm::end(); ?>
<?php endif;?>           

backend/views/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Create User';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create User', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'username',
            'auth_key',
            'password_hash',
            'password_reset_token',
            //'email:email',
            //'status',
            //'created_at',
            //'updated_at',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

backend/views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = 'Update User: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,'changePasswordModel'=>$changePasswordModel   
    ]) ?>

</div>

backend/views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\User */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            // 'id',
            'username',
            // 'auth_key',
            // 'password_hash',
            // 'password_reset_token',
            'email:email',
            'status',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>