common/models/Celebrity.php
<?php

namespace common\models;
use yii\web\UploadedFile;     
use Yii;
use yii\behaviors\SluggableBehavior;    
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use common\models\Award;
use common\models\Filmography;
/**
 * This is the model class for table "celebrity".
 *
 * @property int $id
 * @property string $name
 * @property string $about
 * @property string $title  
 * @property int $type 1=artist, 2=model
 * @property string $filmography
 * @property string $awards
 * @property int $status 0=no, 1=yes
 * @property string $slug
 * @property string $image
 * @property string $created_at
 * @property string $updated_at
 */
class Celebrity extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'celebrity';
    }
    
    static $type = [
        1 => 'Artist',
        2 => 'Model'
    ];
    static $status = [
        0 => 'Inactive',
        1 => 'Active'
    ];
    /**
     * {@inheritdoc}
     */

    public function behaviors()   
    {
            return  [
                [
                'class' => SluggableBehavior::className(),
                'attribute' => 'name',
                // 'slugAttribute' => 'slug',
                ],
                [
                    'class' => TimestampBehavior::className(),   
                    'createdAtAttribute' => 'created_at',
                    'updatedAtAttribute' => 'updated_at',
                    'value' =>  new Expression('NOW()'),     
                ], 
            ];
    } 

    public function rules()     
    {
        return [
            [['name', 'about', 'title', 'type'], 'required'],
            [['about', 'filmography', 'awards'], 'string'],
            [['type', 'status'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['name', 'title', 'slug', 'image'], 'string', 'max' => 200],
        ];
    }    

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'about' => 'About',
            'title' => 'Title',
            'type' => 'Type',
            'filmography' => 'Filmography',   
            'awards' => 'Awards',
            'status' => 'Status',
            'slug' => 'Slug',
            'image' => 'Image',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];  
    }


    public function saveFile()    
    { 
        // $model = new TravelAgency();
        $instance = UploadedFile::getInstance($this, 'image');      
        if ($instance) {
            $image_name = $instance->baseName . '.' . $instance->extension;                          
                $instance->saveAs('uploads/celebrity/' . $image_name);
               return $this->image = $image_name;

        }else{
			if(!empty($this->oldAttributes)) return $this->image = $this->oldAttributes['image'];
		}
        return true;  
    }    

    public function getAward()            
    {
       return $this->hasOne(Award::className(), ['celebrity_id' => 'id']);
    }
    public function getFilmography()            
    {
       return $this->hasOne(Filmography::className(), ['celebrity_id' => 'id']);
    }
}

backend/controllers/CelebrityController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Celebrity;
use common\models\CelebritySearch;
use common\models\CelebrityGallery;
use common\models\CelebrityGallerySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use common\models\Filmography;
use common\models\Award;
use yii\base\Model;

/**
 * CelebrityController implements the CRUD actions for Celebrity model.
 */
class CelebrityController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Celebrity models.
     * @return mixed
     */
    public function actionIndex()
    {
        $this->layout= 'container';                                                                  
        $searchModel = new CelebritySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Celebrity model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)        
    {   
        $this->layout= 'container';     
        $celebrity_gallery_model = new CelebrityGallery();   
        $searchModel = new CelebrityGallerySearch();
        $dataProvider = $searchModel->searchVideoGallery($id);  
        $award = Award::find()->where(['celebrity_id'=>$id])->all();
        $filmography = Filmography::find()->where(['celebrity_id'=>$id])->all();
        // $gallery_data = CelebrityGallery::find()->where(['celebrity_id'=>$id])->all(); 
        // print_r(Yii::$app->request->post());exit;
        return $this->render('view', [
            'model' => $this->findModel($id),
            'celebrity_gallery_model' =>$celebrity_gallery_model,
            'dataProvider'=>$dataProvider,
            'award'=>$award,
            'filmography'=>$filmography,
            'searchModel' => $searchModel    
        ]);
    }

    /**
     * Creates a new Celebrity model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $this->layout= 'container';   

        $model = new Celebrity();

        $filmography_count = Yii::$app->request->post()?Yii::$app->request->post()['Filmography']['filmographys_count']:1;
        
        $award_count = Yii::$app->request->post()?Yii::$app->request->post()['Award']['awards_count']:1;
        $filmography_model = [new Filmography()];                 
        $award_model = [new Award()];  

        for($i = 1; $i < $filmography_count; $i++) {  
            $filmography_model[] = new Filmography();             
        }   
        for($i = 1; $i < $award_count; $i++) {  
            $award_model[] = new Award();               
        }  
        
        $celebrity_valid = false;
        // print_r(Yii::$app->request->post());exit;
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            
            $celebrity_valid = true;
        }

        $filmography_valid = false;
        if (Model::loadMultiple($filmography_model, Yii::$app->request->post()) && Model::validateMultiple($filmography_model)) {
          $filmography_valid = true; 
        }
        $award_valid = false;
        if (Model::loadMultiple($award_model, Yii::$app->request->post()) && Model::validateMultiple($award_model)) {
          $award_valid = true; 
        }
                
        if($celebrity_valid && $filmography_valid &&  $award_valid ){
             $model->saveFile();         
            $model->save(false);     
            foreach ($filmography_model as $filmography) {    
                $filmography->celebrity_id =$model->id;
                $filmography->save(false);
            }
            foreach ($award_model as $award) {  
                $award->celebrity_id =$model->id;
                $award->save(false);
            }
         
           return $this->redirect(['view', 'id' => $model->id]);         
    }

        return $this->render('create', [
            'model' => $model,
            'filmography_model' => $filmography_model,
            'award_model'=>$award_model,
        ]);
    }      

    public function actionVideoGallerySave($id){          
		if(Yii::$app->request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;

			$celebritygalleryModel = new CelebrityGallery();
			$celebrity_model = $this->findModel($id);  
            // $celebritygalleryModel->scenario = 'update';
			if($celebritygalleryModel->load(Yii::$app->request->post()) && $celebritygalleryModel->validate()){
                $celebritygalleryModel->celebrity_id = $id;
                $celebritygalleryModel->type = 2;
				$celebritygalleryModel->save(false);
				echo json_encode([
				'success'=>1,    
				'data'=>$this->renderAjax('celebrity_gallery_form', [
                'model'=>$celebritygalleryModel,'celebrity_model'=>$celebrity_model
                
            ])
            ]);
            
			}else{
				echo json_encode([
				'success'=>0,
				'data'=>$this->renderAjax('celebrity_gallery_form', [
                 'model'=>$celebritygalleryModel,'celebrity_model'=>$celebrity_model
				])
			]);
			}
			
				
			
			Yii::$app->end();         
			
		}
	}

    /**
     * Updates an existing Celebrity model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)   
    {       
        $this->layout= 'container';                                                                  
        $model = $this->findModel($id);
        $filmography_model = Filmography::find()->where(['celebrity_id'=>$id])->all();
        $award_model = Award::find()->where(['celebrity_id'=>$id])->all();  

        $filmography_count = Yii::$app->request->post()?(Yii::$app->request->post()['Filmography']['filmographys_count'] - count($filmography_model)):0;
        
        $award_count = Yii::$app->request->post()?(Yii::$app->request->post()['Award']['awards_count']- count($award_model)):0;


        for($i = 0; $i < $filmography_count; $i++) {  
            $filmography_model[] = new Filmography();             
        }   
        for($i = 0; $i < $award_count; $i++) {  
            $award_model[] = new Award();               
        }  
        
        $celebrity_valid = false;
        // print_r(Yii::$app->request->post());exit;
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            
            $celebrity_valid = true;
        }

        $filmography_valid = false;
        if (Model::loadMultiple($filmography_model, Yii::$app->request->post()) && Model::validateMultiple($filmography_model)) {
          $filmography_valid = true; 
        }
        $award_valid = false;
        if (Model::loadMultiple($award_model, Yii::$app->request->post()) && Model::validateMultiple($award_model)) {
          $award_valid = true; 
        }
                
        if($celebrity_valid && $filmography_valid &&  $award_valid ){
             $model->saveFile();         
            $model->save(false);     
            foreach ($filmography_model as $filmography) {    
                $filmography->celebrity_id =$model->id;
                $filmography->save(false);
            }
            foreach ($award_model as $award) {  
                $award->celebrity_id =$model->id;
                $award->save(false);
            }
         
           return $this->redirect(['view', 'id' => $model->id]);         
        }
   
        return $this->render('update', [      
            'model' => $model,
            'filmography_model' => $filmography_model,
            'award_model'=>$award_model,
        ]);
    }

    /**
     * Deletes an existing Celebrity model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->layout= 'container';                                                                  
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Celebrity model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Celebrity the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Celebrity::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/celebrity/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;  
use yii\helpers\Url;  

/* @var $this yii\web\View */
/* @var $model common\models\Celebrity */
/* @var $form yii\widgets\ActiveForm */
// print_r($award_model);exit;
?>

    <div class="celebrity-forms">     
        <?php $form = ActiveForm::begin(['id'=>'celebrity-form']); ?>

            <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>   

            <?= $form->field($model, 'about')->textarea(['rows' => 6]) ?>  

            <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'type')->dropDownList($model::$type,['prompt'=>"select type"]) ?>

            <?= $form->field($model, 'image')->fileInput(['maxlength' => true]) ?>   
            <?php    
                if(!empty($model->image) && !$model->isNewRecord){
                    echo Html::img(Url::base().'/uploads/celebrity/' . $model->image, [
                                    'width' => '100px'
                                ]);
                }?> 
    </div>
    
    <div class="award-form">   

        <div class="row">
            <div class="col-md-4">
            <h2> Awards</h2>
                <?= Html::a('Add award', '#', ['style'=>'margin-top: -30px','class'=>'pull-right btn btn-primary add-more','data-eleid'=>'award_count']) ?>
            </div>
        </div>  
        <hr />  
         
        <?php foreach ($award_model as $award_index => $award) {
            $award_count = $award_index+1;
        ?>
        <div class="each-data row" style="background:1px solid #fcfcfc">
            
            <div class="col-md-4">
                <?= $form->field($award, "[$award_index]name")->textInput(['maxlength' => true]) ?>
            </div>
            <div class="col-md-4">
                <?= $form->field($award, "[$award_index]release_date")->textInput(['class'=>'form-control fc-datepicker','placeholder'=>"Year of release"]) ?>
            </div>
        </div>
        <?php }?>        
        
        <input type="hidden" value="<?=$award_count;?>" name="Award[awards_count]" id="award_count" />
    </div>
    <div class="filmography-form">   

        <div class="row">
            <div class="col-md-4">
            <h2> Filmography</h2>
                <?= Html::a('Add filmography', '#', ['style'=>'margin-top: -30px','class'=>'pull-right btn btn-primary add-more','data-eleid'=>'filmography_count']) ?>
            </div>
        </div>
        <hr />  
         
        <?php foreach ($filmography_model as $filmography_index => $filmography) {
        $filmography_count = $filmography_index+1;
        ?>
        <div class="each-data row" style="background:1px solid #fcfcfc">
            
            <div class="col-md-4">
                <?= $form->field($filmography, "[$filmography_index]name")->textInput(['maxlength' => true]) ?>
            </div>
            <div class="col-md-4">
                <?= $form->field($filmography, "[$filmography_index]release_date")->textInput(['class'=>'form-control fc-datepicker','placeholder'=>"Year of release"]) ?>
            </div>
        </div>
        <?php }?>        
        
        <input type="hidden" value="<?=$filmography_count;?>" name="Filmography[filmographys_count]" id="filmography_count" />
    </div>


    <?= $form->field($model, 'status')->dropDownList($model::$status,['prompt'=>"select status"]) ?>
   
    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

           

<style>



       
</style>
<?php         
$js = <<<JS
    $(document).ready(function(){               
    $('.fc-datepicker').datepicker({
            dateFormat: 'yy',
            changeYear: true,
          showOtherMonths: true,
          selectOtherMonths: true
        });

    $(".add-more").on('click',function(ev){
            ev.preventDefault();
            var obj = $(this);
            var ele = $("#"+obj.data("eleid"));
            count = ele.val();
            ele.val(parseInt(count) + 1);
            $("#celebrity-form").submit();
        });    


        })
JS;
$this->registerJS($js);
?> 

backend/views/celebrity/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\CelebritySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="celebrity-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'about') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'type') ?>

    <?php // echo $form->field($model, 'filmography') ?>

    <?php // echo $form->field($model, 'awards') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'slug') ?>

    <?php // echo $form->field($model, 'image') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/celebrity/celebrity_gallery_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;  
use common\models\Category;      
use yii\helpers\ArrayHelper;          
/* @var $this yii\web\View */
/* @var $model common\models\CelebrityGallery */
/* @var $form yii\widgets\ActiveForm */
// print_r($model);exit;     
?>

    <?php $form = ActiveForm::begin(['id'=>'gallery']); ?>            

    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'youtube_id')->textInput(['maxlength' => true]) ?>     
        </div>
        <div class="form-group gallery_btn">
            <?= Html::submitButton('Add', ['class' => 'btn btn-success','id'=>'celebrity_gallery_form','data-aurl'=>Yii::$app->urlManager->createUrl(['celebrity/video-gallery-save','id'=>$celebrity_model->id]),'data-formid'=>'gallery_form'])?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>    

<style>
.gallery_btn{
    margin-top: 28px;
}
</style>


<?php
$js =<<<JS
	$("body").on("click",'#celebrity_gallery_form',function(ev){   
		ev.preventDefault();
		
		var obj = $(this);
        // console.log(obj);
		$.ajax({
			type:'post',
			url:obj.data('aurl'),
			data:$("body #gallery").serialize(),     
			dataType:'json',
			success:function(res){
				if(res.success==1){
                // console.log(res);
					$("body #gallery")[0].reset();
					// $.pjax.defaults.timeout = false;
				}else{
					$("body #tab_2").html(res.data);
				}
			}
		})
		});
JS;
$this->registerJS($js);           
?>

backend/views/celebrity/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Celebrity */

$this->title = 'Create Celebrity';
$this->params['breadcrumbs'][] = ['label' => 'Celebrities', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="celebrity-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'filmography_model' => $filmography_model,
        'award_model'=>$award_model,
    ]) ?>

</div>

backend/views/celebrity/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel common\models\CelebritySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Celebrities';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="celebrity-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Celebrity', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],   

           // 'id',
            'name',
            'about:ntext',  
            'title',
            [
                'attribute' => 'image',     
                'filter' => false,  
                'format' => 'html',                
                'value' => function($model){
                    // echo Url::base();exit;
                    return  Html::img(Url::base().'/uploads/celebrity/'. $model->image,['width' => '60px',
                    'height' => '60px']);           
                }   
            ], 
            [
                'attribute' => 'type',
                'filter' => false,  
                'value' => function($model){
                    return $model::$type[$model->type];      
                }   
            ], 

            //'filmography:ntext',
            //'awards:ntext',
            //'status',
            //'slug',
            //'image',
            //'created_at',
            //'updated_at',

           ['class' => 'common\components\ActionColumn'], 
        ],
    ]); ?>
</div>

backend/views/celebrity/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Celebrity */

$this->title = 'Update Celebrity: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Celebrities', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="celebrity-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'filmography_model' => $filmography_model,
        'award_model'=>$award_model,
    ]) ?>

</div>